marlow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="accounts/login.html", redirect_authenticated_user=True),name='login'),
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('change/', auth_views.PasswordChangeView.as_view(success_url="/"), name="passchange"),
    path('votepage/', include("votes.urls", namespace="votes")),
]

votes/urls.py
from django.urls import path, include
from . import views

app_name = 'votes'

urlpatterns = [
    path('', views.votes,name='votepage'),
    path('castvote/<int:pk>/', views.cast_vote, name="cast-vote"),
    path('weekly_results/', views.weekly_results, name='weekly'),
    path('yet_to_vote/', views.not_voted, name='yet_to_vote'),
    path('cumulative_results/', views.cumulative_results, name='total'),

]

votes/models.py
from django.db import models
from django.core.validators  import MinValueValidator, MaxValueValidator
from django.contrib.auth import get_user_model
from datetime import datetime
from django.contrib import auth
# Create your models here.

# Create your models here.
User = get_user_model()

class Teams(models.Model):
    team_name = models.CharField("Team Name", max_length=255)

    def __str__(self):
        return self.team_name

class Fixture(models.Model):
    season = models.PositiveIntegerField(blank=False, null=False,
            validators=[
                MinValueValidator(2019),
                MaxValueValidator(datetime.now().year)])
    round = models.PositiveIntegerField(blank=False, null=False)
    game_time = models.DateTimeField(blank=True, null=True)
    opponent = models.ForeignKey(Teams, on_delete=models.SET_NULL, null=True)
    goals_for = models.PositiveIntegerField(null=True)
    goals_againt = models.PositiveIntegerField(null=True)

    def __str__(self):
        return 'Round '+str(self.round)+ ' ('+str(self.season)+ ')'

class PlayerVotes(models.Model):
    voter = models.ForeignKey(User,related_name="voter" ,on_delete=models.SET_NULL, null=True)
    round = models.ForeignKey(Fixture, on_delete=models.SET_NULL, null=True)
    three_votes = models.ForeignKey(User,related_name="three_votes" ,on_delete=models.SET_NULL, null=True)
    two_votes = models.ForeignKey(User,related_name="two_votes" ,on_delete=models.SET_NULL, null=True)
    one_vote = models.ForeignKey(User,related_name="one_vote", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.voter) + '('+str(self.round) + ')'

votes/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

users = User.objects.all()
players = []
for user in users:
    players.append((user.first_name+' '+user.last_name,user.first_name+' '+user.last_name))

class PlayerVotesForm(forms.ModelForm):
    class Meta:
        model = models.PlayerVotes
        fields = ('three_votes', 'two_votes', 'one_vote')


    def __init__(self, user, round, *args, **kwargs):
        self.voter = user
        self.round = round
        super(PlayerVotesForm, self).__init__(*args, **kwargs)

    def clean(self):
        all_clean_data = super().clean()
        three_votes = all_clean_data.get('three_votes')
        two_votes = all_clean_data.get('two_votes')
        one_vote = all_clean_data.get('one_vote')

        if three_votes == two_votes or three_votes == one_vote or two_votes == one_vote:
            raise forms.ValidationError('You cannot vote for the same person more than once.')
        if self.voter == three_votes or self.voter == two_votes or self.voter == one_vote:
            raise forms.ValidationError('You cannot vote for yourself!')


    def save(self):
        player_votes = super(PlayerVotesForm, self).save(commit=False)
        player_votes.voter = self.voter
        player_votes.round = self.round
        player_votes.save()
        return player_votes

votes/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from . import models
from . import forms
from datetime import datetime
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Count
from operator import itemgetter

# Create your views here.

def get_full_name(self):
    return self.first_name+' '+self.last_name

User.add_to_class("__str__", get_full_name)


@login_required
def votes(request, form_failed = None):
    fixtures = models.Fixture.objects.filter(season=datetime.today().year) #get all the fixtures for the current year
    games = {}
    for game in fixtures:
        if models.PlayerVotes.objects.filter(voter=request.user, round=game).exists(): #if player has already voted
            status = 'Y'
        else:
            status = 'N'
        games[game] = [forms.PlayerVotesForm(user=request.user, round=game), status] #save voting form
    if form_failed is None: #if there are no errors coming back
        return render(request, 'votes/display.html', context={'games':games, 'failed': None} )
    else: #render form with errors
        return render(request, 'votes/display.html', context={'games':games, 'failed': form_failed} )

@login_required
def cast_vote(request, pk):
    game = get_object_or_404(models.Fixture, pk=pk)
    form_failed = {}
    if request.method == "POST":
        form = forms.PlayerVotesForm(request.user, game,request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('votes:votepage'))
        else:
            form_failed[game] = form.errors
            return votes(request, form_failed)

@staff_member_required
def not_voted(request):
    games={}
    for game in models.Fixture.objects.filter(season=datetime.today().year):
        not_voted = []
        for user in User.objects.all():
            if not models.PlayerVotes.objects.filter(voter=user,round=game):
                not_voted.append(user)
        games[game] = not_voted
    return render(request, 'votes/not_voted.html', {'games':games})


@staff_member_required
def weekly_results(request):
    fixtures = models.Fixture.objects.filter(season=datetime.today().year) #get all the fixtures for the current year
    votes = ['three_votes','two_votes','one_vote']
    games = {}
    for game in fixtures:
        temp_dict = {}
        temp_list = []
        for count, vts in enumerate(votes):
            vote=models.PlayerVotes.objects.filter(round=game).values(vts).annotate(Count(vts))
            for each in vote:
                if each[vts] in temp_dict.keys():
                    temp_dict[each[vts]][count] =  temp_dict[each[vts]][count] + each[str(vts)+"__count"]
                else:
                    if count == 0:
                        temp_dict[each[vts]] = [each[str(vts)+"__count"],0,0]
                    elif count ==1:
                        temp_dict[each[vts]] = [0,each[str(vts)+"__count"],0]
                    else:
                        temp_dict[each[vts]] = [0,0,each[str(vts)+"__count"]]

        for key in temp_dict.keys():

            temp_list.append([User.objects.get(pk=key), int(temp_dict[key][0])*3+int(temp_dict[key][1])*2+int(temp_dict[key][2])*1])

        games[game] = sorted(temp_list, key=itemgetter(1), reverse=True)
    return render(request, 'votes/weekly_results.html', {'games':games})

@staff_member_required
def cumulative_results(request):
    fixtures = models.Fixture.objects.filter(season=datetime.today().year) #get all the fixtures for the current year
    votes = ['three_votes','two_votes','one_vote']
    running_count = {}
    games = {}
    for game in fixtures:
        temp_dict = {}
        temp_list = []
        for count, vts in enumerate(votes):
            vote=models.PlayerVotes.objects.filter(round=game).values(vts).annotate(Count(vts))
            for each in vote:
                if each[vts] in temp_dict.keys():
                    temp_dict[each[vts]][count] =  temp_dict[each[vts]][count] + each[str(vts)+"__count"]
                else:
                    if count == 0:
                        temp_dict[each[vts]] = [each[str(vts)+"__count"],0,0]
                    elif count ==1:
                        temp_dict[each[vts]] = [0,each[str(vts)+"__count"],0]
                    else:
                        temp_dict[each[vts]] = [0,0,each[str(vts)+"__count"]]


        for key in temp_dict.keys():

            temp_list.append([User.objects.get(pk=key), int(temp_dict[key][0])*3+int(temp_dict[key][1])*2+int(temp_dict[key][2])*1])

        for data in temp_list:
            if data[0] in running_count.keys():
                running_count[data[0]] = running_count[data[0]]  + data[1]
            else:
                running_count[data[0]] = data[1]
        list_running_counter = [[k,v] for k,v in running_count.items()]

        games[game] = sorted(list_running_counter, key=itemgetter(1), reverse=True)
    return render(request, 'votes/cumulative_results.html', {'games':games})

votes/templates/votes/base.html
<!DOCTYPE html>
{%load vote_tags%}
{% load crispy_forms_tags %}
<html>
<head>
  <title>Bootstrap Example</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'votes:votepage' %}">Marlow</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    {% if request.user.is_staff %}
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'votes:yet_to_vote' %}">Yet to Vote</a>
      <a class="nav-item nav-link" href="{% url 'votes:weekly' %}">Weekly Results</a>
      <a class="nav-item nav-link" href="{% url 'votes:total' %}">Cumulative Results</a>
      <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin Portal</a>
    </div>
    {% endif %}
    <div class="navbar-nav ml-auto">
      <a class="nav-item nav-link" href="{% url 'passchange' %}">Change Password</a>
      <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}
</body>
</html>

votes/templates/votes/cumulative_results.html
{% extends "votes/base.html" %}
{%load vote_tags%}
{% block content %}
<br>
<div class="container">
  <h1>Marlow Championship Voting Cumulative Results</h1>

  <div id="accordion">
    {%for game,form in games.items%}
    <div class="card">
      <div class="card-header">
        <a class="card-link" data-toggle="collapse" href="#collapse{{game.round}}">
          Round {{game.round}}: {{game.opponent}}
        </a>
      </div>
      <div id="collapse{{game.round}}" class="collapse" data-parent="#accordion">
        <div class="card-body">
          <h3>Round {{game.round}}</h3>
          <h4>Opposition: {{game.opponent}}</h4>
          <h4>Result: {{game.goals_for}}-{{game.goals_againt}} {%if game.goals_for > game.goals_againt%} Win{%elif game.goals_for == game.goals_againt %} Draw {%else%} Loss {%endif%} </h4>
          <h4>Game Time: {{game.game_time|date:'d-m-Y H:i'}}</h4>
          <br>
          <br>
          <h3>Best on ground votes</h3>

          {% if game.game_time|is_future %}
          <h4>Voting for this round is not open yet!</h4>
          {%elif not form%}
          <h4>No votes recorded yet!</h4>
          {% else %}
          <ol>
            {% for name in form %}
            <li>{{name.0}}: {{name.1}} Votes</li>
            {%endfor%}
          </ol>

          {% endif %}
        </div>
      </div>
    {%endfor%}
  </div>
</div>

{% endblock %}

votes/templates/votes/display.html
{% extends "votes/base.html" %}
{%load vote_tags%}
{% load crispy_forms_tags %}
{% block content %}

<br>
<div class="container">
  <h1>Marlow Championship Voting</h1>

  <p>Please note votes are final and once submitted cannot be changed. </p>
  <div id="accordion">
    {%for game,form in games.items%}
    <div class="card">
      <div class="card-header">
        <a class="card-link" data-toggle="collapse" href="#collapse{{game.round}}">
          Round {{game.round}}: {{game.opponent}}
        </a>
      </div>
      {%if failed is none%}
        {%if game.game_time|is_current%}
        <div id="collapse{{game.round}}" class="collapse show" data-parent="#accordion">

        {%elif failed.round == game.round%}
        <div id="collapse{{game.round}}" class="collapse show" data-parent="#accordion">
        {%else%}
        <div id="collapse{{game.round}}" class="collapse" data-parent="#accordion">
        {%endif%}

      {%else%}
        {%for fgame, fkey in failed.items%}

          {%if fgame.round == game.round%}
          <div id="collapse{{game.round}}" class="collapse show" data-parent="#accordion">
              {%for field, er in fkey.items%}
              <div class="alert alert-danger">
                  <strong>{{ er|escape }}</strong>
              </div>
              {%endfor%}

          {%else%}
          <div id="collapse{{game.round}}" class="collapse" data-parent="#accordion">
          {%endif%}
        {%endfor%}
      {%endif%}
        <div class="card-body">
          <h3>Round {{game.round}}</h3>
          <h4>Opposition: {{game.opponent}}</h4>
          <h4>Result: {{game.goals_for}}-{{game.goals_againt}} {%if game.goals_for > game.goals_againt%} Win{%elif game.goals_for == game.goals_againt %} Draw {%else%} Loss {%endif%} </h4>
          <h4>Game Time: {{game.game_time|date:'d-m-Y H:i'}}</h4>
          <br>
          <br>
          <h3>Best on ground votes</h3>

          {% if game.game_time|is_future %}
          <h4>Voting for this round is not open yet!</h4>
          {%elif form.1 == 'Y'%}
          <h4>You have already voted for this round!</h4>
          {% elif game.opponent == 'BYE' %}
          <h4>You cannot vote on a BYE.</h4>

          {% else %}

          <form action="{% url 'votes:cast-vote' game.pk %}" method="POST">
            {% csrf_token %}
             {{ form.0|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
          {% endif %}

        </div>
      </div>
    </div>
    {%endfor%}
  </div>
</div>

{% endblock %}

votes/templates/votes/not_voted.html
{% extends "votes/base.html" %}
{%load vote_tags%}
{% block content %}
<br>
<div class="container">
  <h1>People yet to vote</h1>
  <div id="accordion">
    {%for game,form in games.items%}
    <div class="card">
      <div class="card-header">
        <a class="card-link" data-toggle="collapse" href="#collapse{{game.round}}">
          Round {{game.round}}: {{game.opponent}}
        </a>
      </div>
      <div id="collapse{{game.round}}" class="collapse" data-parent="#accordion">
        <div class="card-body">
          <h3>Round {{game.round}}</h3>
          <h4>Opposition: {{game.opponent}}</h4>
          <h4>Result: {{game.goals_for}}-{{game.goals_againt}} {%if game.goals_for > game.goals_againt%} Win{%elif game.goals_for == game.goals_againt %} Draw {%else%} Loss {%endif%} </h4>
          <h4>Game Time: {{game.game_time|date:'d-m-Y H:i'}}</h4>
          <br>
          <br>
          <h3>Best on ground votes</h3>

          {% if game.game_time|is_future %}
          <h4>Voting for this round is not open yet!</h4>
          {% else %}
            {%if form%}
            <h4>The following people have not voted:</h4>
            <ul>
              {% for name in form %}
              <li>{{name}}</li>
              {%endfor%}
            </ul>
            {%else%}
            <h4>Everyone has voted for this round.</h4>
            {%endif%}

          {% endif %}
        </div>
      </div>
    {%endfor%}
  </div>
</div>

{% endblock %}

votes/templates/votes/placeholder.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Placeholder</title>
  </head>
  <body>
    <p>Placeholder!</p>
  </body>
</html>

votes/templates/votes/weekly_results.html
{% extends "votes/base.html" %}
{%load vote_tags%}
{% block content %}
<br>
<div class="container">
  <h1>Marlow Championship Voting Weekly Results</h1>

  <div id="accordion">
    {%for game,form in games.items%}
    <div class="card">
      <div class="card-header">
        <a class="card-link" data-toggle="collapse" href="#collapse{{game.round}}">
          Round {{game.round}}: {{game.opponent}}
        </a>
      </div>
      <div id="collapse{{game.round}}" class="collapse" data-parent="#accordion">
        <div class="card-body">
          <h3>Round {{game.round}}</h3>
          <h4>Opposition: {{game.opponent}}</h4>
          <h4>Result: {{game.goals_for}}-{{game.goals_againt}} {%if game.goals_for > game.goals_againt%} Win{%elif game.goals_for == game.goals_againt %} Draw {%else%} Loss {%endif%} </h4>
          <h4>Game Time: {{game.game_time|date:'d-m-Y H:i'}}</h4>
          <br>
          <br>
          <h3>Best on ground votes</h3>

          {% if game.game_time|is_future %}
          <h4>Voting for this round is not open yet!</h4>
          {%elif not form%}
          <h4>No votes recorded yet!</h4>
          {% else %}
          <ol>
            {% for name in form %}
            <li>{{name.0}}: {{name.1}} Votes</li>
            {%endfor%}
          </ol>

          {% endif %}
        </div>
      </div>
    {%endfor%}
  </div>
</div>

{% endblock %}